// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUtt-Oiwg77yW_Fk0eIzbtwZ1S2xRhArg',
    appId: '1:17171228074:web:6ac381cecca5c0136537d3',
    messagingSenderId: '17171228074',
    projectId: 'sketch-f5ced',
    authDomain: 'sketch-f5ced.firebaseapp.com',
    storageBucket: 'sketch-f5ced.firebasestorage.app',
    measurementId: 'G-M9BXYQZQYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTpvkXAIEQm5SPZnad32fOizn0WyWS9HA',
    appId: '1:17171228074:android:5418be3dc12864916537d3',
    messagingSenderId: '17171228074',
    projectId: 'sketch-f5ced',
    storageBucket: 'sketch-f5ced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOZgcwAuYGo2gOeuVu1ng8nFo215vLZuQ',
    appId: '1:17171228074:ios:4ce1bb49b93320026537d3',
    messagingSenderId: '17171228074',
    projectId: 'sketch-f5ced',
    storageBucket: 'sketch-f5ced.firebasestorage.app',
    androidClientId:
        '17171228074-v1cqhhb9f8th3jju89o8po5fgcnec001.apps.googleusercontent.com',
    iosClientId:
        '17171228074-cppti91lmutmnn7emovp790lmv6iejoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sketch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOZgcwAuYGo2gOeuVu1ng8nFo215vLZuQ',
    appId: '1:17171228074:ios:4ce1bb49b93320026537d3',
    messagingSenderId: '17171228074',
    projectId: 'sketch-f5ced',
    storageBucket: 'sketch-f5ced.firebasestorage.app',
    androidClientId:
        '17171228074-v1cqhhb9f8th3jju89o8po5fgcnec001.apps.googleusercontent.com',
    iosClientId:
        '17171228074-cppti91lmutmnn7emovp790lmv6iejoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sketch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUtt-Oiwg77yW_Fk0eIzbtwZ1S2xRhArg',
    appId: '1:17171228074:web:fa7f5df606d422df6537d3',
    messagingSenderId: '17171228074',
    projectId: 'sketch-f5ced',
    authDomain: 'sketch-f5ced.firebaseapp.com',
    storageBucket: 'sketch-f5ced.firebasestorage.app',
    measurementId: 'G-HBQ0V54LKC',
  );
}
